import Head from "next/head";
import { Inter } from "@next/font/google";
import HomeContent from "../components/Home/HomeContent";
import { GetServerSideProps } from "next";

const inter = Inter({ subsets: ["latin"] });


export default function Home({ data }: any) {

  return (
    <>
      <Head>
        <title>Educine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomeContent data={data}></HomeContent>
      </main>
    </>
  );
}


export const getStaticProps = async () => {
  const res = await fetch("https://session-solutions-server.vercel.app/category");
  const data = await res.json();

  return {
    props: {
      data
    },
  };
};